version: "3.4"
services:
  echo-server:
    container_name: "echo-server"
    build:
      context: .
      target: base
      args:
        PORT: 8080
    command: "air"
    ports:
      - "8080:8080"
    volumes:
      - .:/go/app/base
